spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderManagement
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  mail:
      host: smtp.gmail.com
      port: 587
      username: bibek.bhattarai831@gmail.com
      password: bppd jkwk krrf lccv
      properties:
        mail:
         smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #converts underscore of db into camelcase