spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/orderManagement
    url: jdbc:postgresql://dpg-cq57rc88fa8c7382q5t0-a.singapore-postgres.render.com/orderayo_ditk
#    username: postgres
    username: bibek
#    password: 1234
    password: GiaB9tcvuHh6oXTW6Panow1iHYUjLP2a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  mail:
      host: smtp.gmail.com
      port: 587
      username: bibek.bhattarai83@gmail.com
      password: plia kukk nnyo hlci
      properties:
        mail:
         smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #converts underscore of db into camelcase